version: '3.4'

services:
  testapi:
    image: gcr.io.testapi.dontupload:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_testapi$
    volumes:
      - C:\Users\kwa\Desktop\git\dotnet-aspnet-docker\TestApi:/app
      - C:\Users\kwa\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_testapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_testapi$ bin/Debug/netcoreapp2.0/TestApi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
